
import { Theme, ThemeConfig, Message } from './types';

export const THEMES: Record<Theme, ThemeConfig> = {
  [Theme.NEBULA]: {
    name: 'Nebula',
    background: 'bg-gray-900',
    chatBackground: 'bg-gray-800',
    userBubble: 'bg-violet-600',
    userText: 'text-white',
    botBubble: 'bg-gray-700',
    botText: 'text-gray-200',
    inputBackground: 'bg-gray-700',
    inputText: 'text-white',
    button: 'bg-violet-600',
    buttonHover: 'hover:bg-violet-500',
    borderColor: 'border-gray-600',
  },
  [Theme.MINTY]: {
    name: 'Minty Fresh',
    background: 'bg-emerald-50',
    chatBackground: 'bg-white',
    userBubble: 'bg-emerald-500',
    userText: 'text-white',
    botBubble: 'bg-gray-100',
    botText: 'text-gray-800',
    inputBackground: 'bg-gray-100',
    inputText: 'text-gray-800',
    button: 'bg-emerald-500',
    buttonHover: 'hover:bg-emerald-600',
    borderColor: 'border-gray-200',
  },
  [Theme.SUNSET]: {
    name: 'Sunset Glow',
    background: 'bg-orange-100',
    chatBackground: 'bg-white',
    userBubble: 'bg-rose-500',
    userText: 'text-white',
    botBubble: 'bg-orange-100',
    botText: 'text-rose-900',
    inputBackground: 'bg-white',
    inputText: 'text-gray-800',
    button: 'bg-rose-500',
    buttonHover: 'hover:bg-rose-600',
    borderColor: 'border-orange-200',
  },
  [Theme.MONO]: {
    name: 'Monochrome',
    background: 'bg-gray-200',
    chatBackground: 'bg-white',
    userBubble: 'bg-black',
    userText: 'text-white',
    botBubble: 'bg-gray-200',
    botText: 'text-black',
    inputBackground: 'bg-white',
    inputText: 'text-black',
    button: 'bg-black',
    buttonHover: 'hover:bg-gray-800',
    borderColor: 'border-gray-300',
  },
  [Theme.OCEANIC]: {
    name: 'Oceanic',
    background: 'bg-sky-950',
    chatBackground: 'bg-sky-900',
    userBubble: 'bg-cyan-500',
    userText: 'text-white',
    botBubble: 'bg-sky-800',
    botText: 'text-sky-100',
    inputBackground: 'bg-sky-800',
    inputText: 'text-white',
    button: 'bg-cyan-500',
    buttonHover: 'hover:bg-cyan-600',
    borderColor: 'border-sky-700',
  },
};

export const INITIAL_MESSAGE: Message = {
    id: 'initial',
    sender: 'bot',
    text: 'Hello! I am a Gemini-powered assistant. How can I help you today?',
};
